language: perl
perl:
  - "5.16"

before_install:
  - git clone --branch=master --depth=100 --quiet git://github.com/mamod/JavaScript-Shell.git j_shell
  - cd j_shell
  - cpanm --quiet --installdeps --notest
  - cd ..
  

after_script:
  - "pode ./tests/all.js"
