language: perl
perl:
  - "5.16"

before_install:
  - git clone --branch=master --depth=100 --quiet git://github.com/mamod/JavaScript-Shell.git j_shell
  - cd j_shell
  - "cpanm -n JSON::Any"
  - perl Makefile.PL
  - make && make install
  - cd ..
  

after_script:
  - cd blib/script
  - "pode ./tests/all.js"
